// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmCpUW7TD-eCTxjFyQXV68gX2sx7h5RTY',
    appId: '1:75889539487:web:91590621c3b735f314e5aa',
    messagingSenderId: '75889539487',
    projectId: 'dmi-login-omv',
    authDomain: 'dmi-login-omv.firebaseapp.com',
    storageBucket: 'dmi-login-omv.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkzVuocz0BxfT1QNHNZGBJE4O6YWA_PAY',
    appId: '1:75889539487:android:728fda71a9d90ef714e5aa',
    messagingSenderId: '75889539487',
    projectId: 'dmi-login-omv',
    storageBucket: 'dmi-login-omv.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcpTzaNMLMTxg6898GQsOBLBWjbotqDn8',
    appId: '1:75889539487:ios:670ed1cbdaee695d14e5aa',
    messagingSenderId: '75889539487',
    projectId: 'dmi-login-omv',
    storageBucket: 'dmi-login-omv.firebasestorage.app',
    iosBundleId: 'com.example.dmiOmv10b',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcpTzaNMLMTxg6898GQsOBLBWjbotqDn8',
    appId: '1:75889539487:ios:670ed1cbdaee695d14e5aa',
    messagingSenderId: '75889539487',
    projectId: 'dmi-login-omv',
    storageBucket: 'dmi-login-omv.firebasestorage.app',
    iosBundleId: 'com.example.dmiOmv10b',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmCpUW7TD-eCTxjFyQXV68gX2sx7h5RTY',
    appId: '1:75889539487:web:313fb14e7b77023314e5aa',
    messagingSenderId: '75889539487',
    projectId: 'dmi-login-omv',
    authDomain: 'dmi-login-omv.firebaseapp.com',
    storageBucket: 'dmi-login-omv.firebasestorage.app',
  );
}
